site_name: Stardew Valley Journey
site_url: https://blog.pi3.fun/stardew-valley/
site_author: Pi3-l22
repo_name: Pi3-l22/Stardew_Valley_Journey
repo_url: https://github.com/Pi3-l22/Stardew_Valley_Journey
nav:
  - é¦–é¡µ: index.md
  - Stardew Valley v1.5:
    - ğŸ³ï¸â€ğŸŒˆç›®å½•æ±‡æ€»: list.md
    - äººç‰©ä¿¡æ¯:
      - ğŸ³ï¸â€ğŸŒˆäººç‰©æ±‡æ€»: character/index.md
      - Alex: character/Alex.md
    - ç¤¼ç‰©å–œå¥½: gift.md
    - åœ°ç‚¹ä¿¡æ¯: place.md
    - æ‰“é€ æ¸…å•: build.md
    - æœ¨åŒ å»ºé€ æ¸…å•: carpenter.md
    - é“åŒ å†œå…·å‡çº§æ¸…å•: blacksmith.md
    - æˆ˜æ–—ç‰©å“æ¸…å•: battle.md
    - å·¥åŒ åˆ¶å“æ¸…å•: craftsman.md
    - é£Ÿè°±æ¸…å•: recipe.md
    - æ”¶é›†åŒ…æ¸…å•: collect.md
    - ç´ ææ”¶é›†åœ°ç‚¹(å…¨å­£): material.md
    - å››å­£åœ°å›¾:
      - ğŸ³ï¸â€ğŸŒˆåœ°å›¾æ±‡æ€»: season_map/index.md
      - æ˜¥å­£åœ°å›¾: season_map/spring.md
      - å¤å­£åœ°å›¾: season_map/summer.md
      - ç§‹å­£åœ°å›¾: season_map/fall.md
      - å†¬å­£åœ°å›¾: season_map/winter.md
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: images/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github-alt
  feature:
    - announce.dismiss  # é¡¶éƒ¨å…¬å‘Šæ 
    - content.action.edit  # æºç ç¼–è¾‘
    - content.action.view  # æºç æµè§ˆ
    - content.code.annotate  # ä»£ç æ³¨é‡Š
    - content.code.copy  # ä»£ç å¤åˆ¶
    # - content.code.select  # ä»£ç é€‰æ‹©
    # - content.footnote.tooltips  # è„šæ³¨å·¥å…·æç¤º
    # - content.tabs.link  # æ ‡ç­¾é“¾æ¥
    - content.tooltips  # å·¥å…·æç¤º
    # - header.autohide  # è‡ªåŠ¨éšè—æ ‡é¢˜æ 
    # - navigation.expand  # å¯¼èˆªå±•å¼€
    - navigation.footer  # åº•éƒ¨ä¸Šä¸€é¡µä¸‹ä¸€é¡µå¯¼èˆª
    - navigation.indexes  # ç´¢å¼•å¯¼èˆª
    # - navigation.instant  # å³æ—¶å¯¼èˆª
    # - navigation.instant.prefetch  # å³æ—¶å¯¼èˆªé¢„å–
    # - navigation.instant.progress  # å³æ—¶å¯¼èˆªè¿›åº¦
    # - navigation.prune  # å¯¼èˆªä¿®å‰ª
    - navigation.sections  # å¯¼èˆªç« èŠ‚
    - navigation.tabs  # å¯¼èˆªæ ‡ç­¾
    - navigation.tabs.sticky  # å¯¼èˆªæ ‡ç­¾ç²˜æ€§
    - navigation.top  # è¿”å›é¡¶éƒ¨å¯¼èˆª
    - navigation.tracking  # å¯¼èˆªè·Ÿè¸ª
    - search.highlight  # æœç´¢é«˜äº®
    - search.share  # æœç´¢åˆ†äº«
    - search.suggest  # æœç´¢å»ºè®®
    - toc.follow  # ç›®å½•è·Ÿéš
    # - toc.integrate  # ç›®å½•é›†æˆ
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ¢åˆ°æ·±è‰²æ¨¡å¼

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

extra:
  generator: false  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pi3-l22
    - icon: fontawesome/brands/twitter
      link: https://x.com/liu622511?s=09
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/lc_622_511
    - icon: fontawesome/solid/envelope
      link: mailto:622.511.liuchao@gmail.com

copyright: Copyright &copy; 2021 - 2024 By Pi3-l22

